service: aws-meetup

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: hello.handler
    events:
      - http:
          path: hello
          method: GET
  world:
    handler: world.handler
    events:
      - http:
          path: world/{name}
          method: POST