service: aws-meetup

provider:
  name: aws
  runtime: python3.7

package:
  individually: true
  exclude:
    - ./**

functions:
  hello:
    handler: hello.handler
    package:
      include:
        - hello.py
    events:
      - http:
          path: hello
          method: GET
  world:
    handler: world.handler
    package:
      include:
        - world.py
    events:
      - http:
          path: world/{name}
          method: POST