service: aws-meetup

provider:
  name: aws
  runtime: nodejs10.x

package:
  individually: true
  exclude:
    - ./**

functions:
  hello:
    handler: hello.handler
    package:
      include:
        - hello.js
    events:
      - http:
          path: hello
          method: GET
  world:
    handler: world.handler
    package:
      include:
        - world.js
    events:
      - http:
          path: world/{name}
          method: POST